# Site settings
title: Ender Ahmet Yurt
description: 'Software Engineer'
url: 'enderahmetyurt.github.io'
baseurl: '/'
google_analytics: 'UA-41510931-2'
disqus_shortname: 'ndrx42'

author:
  name: 'Ender Ahmet Yurt'
  email: enderyurt@gmail.com
  twitter_profile: https://twitter.com/ndrx42
  github_profile:  https://github.com/enderahmetyurt
  linkedin_username:  enderahmetyurt
  medium_username: ndrx

# Dependencies
markdown:         kramdown
highlighter:      rouge

paginate: 1

# Custom vars
version: 1.0.0

plugins:
  - jekyll-paginate