# Site settings
title: Ender Ahmet Yurt
description: 'Software Engineer'
url: 'enderahmetyurt.github.io'
baseurl: '/'
tagline: Software Engineer
google_analytics: 'UA-41510931-2'

author:
  name: 'Ender Ahmet Yurt'
  email: enderyurt@gmail.com
  twitter_profile: https://twitter.com/eayurt
  github_profile: https://github.com/enderahmetyurt
  linkedin_profile: https://www.linkedin.com/in/enderahmetyurt/
  youtube_profile: https://www.youtube.com/@eayurt
  medium_username: eayurt

# Dependencies
markdown: kramdown
highlighter: rouge

paginate: 15

# Custom vars
# version: 1.1.0

plugins:
  - jekyll-paginate

# Image settings
image_base: /public/images/

defaults:
  - scope:
      path: 'assets/img'
    values:
      image: true
